### PR TITLE
Split __init__.py into several smaller files

### PR DESCRIPTION
**Pull request by PaulRenvoise**
As suggested by philiptzou in #131 , I took the time to split the huge __init__.py into several smaller files.

This leaves us with 7 files and 1 folder:
- parsedatetime.py
- constants.py
- calendar.py
- context.py
- context_stack.py
- warns.py
- __init__.py
- locales/

I also took the freedom to rename pdtContext and pdtContextStack to Context and ContextStack, as well as moving pdt_locales/ to locales/, for naming consistency purposes.
Splitting __init__.py made me add the code copied from feedburner directly into calendar.py. This also highlighted unused code that I decided to remove.

I'm merging this PR into 3.0 because of the breaking changes this includes:
- pdtContext is now Context
- pdtContextStack is now ContextStack
- pdtLocales is now in Constants.py but exposed via __init__.py
- Version flags are now in Calendar.py but exposed via __init__.py
- debug flag is now both in Calendar.py and Constants.py

Have a nice weekend

---

This change is [Reviewable](https://reviewable.io/reviews/bear/parsedatetime/201)

### CODE REVIEW

**Comment by idpaterson** [comment]
I'll take a closer look later but this seems like a good direction. The inconsistencies were causing problems in naming my new test classes as well, so it would be nice to have stronger naming precedent.

**Comment by PaulRenvoise** [comment]
This PR is really straightforward as I do not have much experience on this project, but it could be the beginning of a discussion about further splitting, by creating modules for NLP processing, or different kind of parsing.

**Comment by idpaterson** [comment]
There are a lot of failing tests here due to import issues. The tests are going to be redone, but even so can you work on getting all of the tests to pass for this PR?

**Comment by PaulRenvoise** [comment]
Tests are passing, just need to improve coverage.

**Pull request closed without merging**
