### PR TITLE
Issue #126 - removed inheritance from object and removed return value…

### PR DESCRIPTION
**Pull request by sbonnick**
Issue #126 - removed inheritance from object and removed return values in comments as both are considered bad form

Not sure yet if this change will fully fix my issue. but it should be changed anyway to be more "pythonic". 

All tests pass.

### CODE REVIEW

**Comment by idpaterson** [comment]
I am curious, why would inheritance from `object` be considered bad form? In Python 3 the inheritance from `object` is implicit but in Python 2 there are significant differences between old-style classes and new-style (inheriting `object`) classes. Is there a specific issue that this addresses? Otherwise it seems to create an unnecessary incompatibility between Python 2 and 3.

**Comment by philiptzou** [comment]
I also don't agree to remove inheritance from `object` unless we want to drop Python 2 support progressively.

**Comment by sbonnick** [comment]
sorry, I do not mean inheritance from object is bad form. I meant that for the @rtype/@return doc tag - and by bad form I mean classes don't need to list their return type by many style guides. Google style guide being one: http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html

for removing object, I was unaware that there was a difference in python 2 between the two class styles. So after researching this, I would agree that it may be best to change this back to inheriting from object for any consumers using python 2. I will make another PR. 

The problem i was attempting to solve was #126 which Pycharm was detecting the return object to be of type "object" and therefore not recognizing the "parse" definition.

**Comment by bear** [comment]
Let's add back the object inheritance item and remove the rtype flag

**Comment by philiptzou** [comment]
@bear the rtype should be changed to `Calendar` and I think it will work in PyCharm.

**Comment by sbonnick** [comment]
do we want it there at all though? it conveys no extra meaning as this is on a class.

I still agree with object going back in. if you want rtype back but with Calendar I will add that too but think its unnecessary on a class.

**Comment by bear** [comment]
Let's add rtype with Calendar and see if that fixes the issue - that would be the smallest change to address the problem.

**Comment by sbonnick** [comment]
pull request created. Thanks guys for spotting the problem with removing object inheritance.

**Pull request merged**
