### PR TITLE
Added 'right now' treated as 'now'

### PR DESCRIPTION
**Pull request by PaulRenvoise**
This change is [Reviewable](https://reviewable.io/reviews/bear/parsedatetime/184)

### CODE REVIEW

**Comment by idpaterson** [comment]
Hi Paul, would you please reset this branch in your fork to the first commit and then force push to remove the French locale commits? That locale will be a great addition once you're ready to submit it. Thanks!

It should be `git checkout master && git reset --hard 4325719604b8ed05b0f85c270e67a8613c8d0c05 && git push origin master -f` assuming the remote for your fork is named *origin*. 

A handy tip for pull requests is to start a new branch for the specific change you're making rather than committing to master on your fork. I can't count how many times I set out to fix one thing in an open source project but in the process bumped into two or three separate issues that needed to be fixed as well. With separate branches you can easily submit multiple independent pull requests.

**Comment by PaulRenvoise** [comment]
Hey,

Sorry for the rookie mistake, I'm not used to do PR and I did not expect my push to update the PR.
I already switched to another branch to work on the French locale, so that's fine!

This PR should now be clean :)

**Comment by idpaterson** [comment]
Looks great, thanks!

**Comment by bear** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/parsedatetime/184)*

**Comment by bear** [comment]
I'm +1 on merging, @idpaterson ?

**Comment by idpaterson** [comment]
Agreed and done :)

**Pull request merged**
