### PR TITLE
fix for issue 95 - parsing 'next june 15'

### PR DESCRIPTION
**Pull request by bear**

### CODE REVIEW

**Comment by idpaterson** [comment]
Nice! I think you'll want to use `offset` rather than `1` for the year delta to support "last june 15" and similar cases.

**Comment by bear** [comment]
oh poo - I had that in an earlier version!

**Comment by bear** [comment]
i'll wait for others to have a chance to chime in before merging

**Comment by philiptzou** [comment]
```python
from parsedatetime import Calendar

cal = Calendar()
print cal.parse('15:00 next june 15')
# (time.struct_time(tm_year=2017, tm_mon=6, tm_mday=15, tm_hour=5, tm_min=4, tm_sec=35, tm_wday=3, tm_yday=166, tm_isdst=-1), 1)
```

But shouldn't be year 2017 right?

**Comment by idpaterson** [comment]
I think it actually is supposed to be 2017 based on the conversation in #99. The default behavior is that "June 15" parses as June 15 2016 (since we have already passed that date in 2015) so "next" adds one year after that. There are a few settings (YearParseStyle, DOWParseStyle and CurrentDOWParseStyle) on Constants that can be used to make "next" and "last" relative to the current calendar year instead.

**Pull request merged**
